apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: persistent-basic
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp2
allowedTopologies:
  - matchLabelExpressions:
    - key: topology.ebs.csi.aws.com/zone
      values: 
      - ap-northeast-2a
      - ap-northeast-2c
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: persistent-advanced
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp3
allowedTopologies:
  - matchLabelExpressions:
    - key: topology.ebs.csi.aws.com/zone
      values:
      - ap-northeast-2a
      - ap-northeast-2c