version: "3.8"
name: "cloudwave_terraform"

services:
  terraform:
    image: matenduel/cloudwave:practice.v2
    command:
      - /bin/bash
      - -c
      - "mkdir -p /terraform && chmod -R 777 /terraform && sleep infinity"
    environment:
      TF_VAR_pem_location: "/root/.ssh"
      # AWS Credentials
      AWS_ACCESS_KEY_ID: "ASIARWRRQM6GXYQXXEFS"
      AWS_SECRET_ACCESS_KEY: "F/cZKks3RF/OFoYevz/DVhDnEUs8aAYi2UMY7O5K"
      AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEGkaDmFwLW5vcnRoZWFzdC0yIkcwRQIgANzyi7nFma+fKRMJ7pHNBkth+wwk60YtXanE2dYRVqMCIQCivzs72cl+ZSzskm2rkoe6uTNHyqxbZfE6D3CwobDwoiqLAwgSEAAaDDExNzE0MTY5NDM0OSIM0V25WWWbVY9kywcHKugCkIXu9MlytD5iThbyUA3Xhf/kAVn8nMB6OOOKvGTUDJlteroWoPmHbZbwj0Gx2YthLb2wT0UEowHIDhmPh/W9lOuIsYrxOSxdRs5kuAzUBx9ZGgzeJpjlybG9zJFeyX6h5d2ywCWVrDbUAlZPlN/9z82gBBMzMvqcehek0a3BLs1XG0GfzIKg6FVzXz3iy/UXFXWj0pyySKRdLewe+9LRHRTjDk3SKuifBY7rT6vZBf3IWGBYMsuqZ834msB2WID5DivrCvJx2YsfWhzYuv3Iekv6PWI8sA/tG+4t4PrPf291DXSDUuaHxpyuu0j1iDcWyZnyUux5sPz288qQhT62onZBMiHv4JbfJ9mtNApS755sif3qKfpR3IECpORl7x2kzYyW6B+3ilY+/gbDGVQgg9ULAvCIYB4ykSmvLZHFUWoNoWac/JUROfq602NEfzNT2cyTCYrkgeXZBhTaXcg1hPfq64MVMsZdMIm7+awGOqYBH5jUBKo3mgxBaf6/kXhHlre8I9GyhO4ssi1lv5miFjyVN8KQa2w/X4hFxeRNvWBvG7pDZImYQIyo1s5IocUUPhi39udaqwHK1+IQUqJuMQGP7w/OtQ4ytLprhBcIxVt2Apyv4K8D4sn5Pz27OwFP0nrCm+3/qBH9A1/hH6H9QKE5EkDlZvZGVx2TIuMliqgCPpUX38l58J0rQYpEXDFIdigMlTaSuA=="
      AWS_REGION: "ap-northeast-2"
    working_dir: /k8s
    volumes:
      # - C:\Users\KDP\.kube:/root/.kube
      - C:\Users\KDT\.kube:/root/.kube
      - ./k8s:/k8s
      - ./src:/terraform
      - credential:/root/.ssh

  gitsync:
    profiles:
      - init
    image: registry.k8s.io/git-sync/git-sync:v4.1.0
    environment:
      GITSYNC_REPO: https://github.com/matenduel/cloudwave
      GITSYNC_ROOT: /tmp/git
      GITSYNC_REF: main
      GITSYNC_DEPTH: 1
      GITSYNC_ONE_TIME: 1
    volumes:
      - ./src:/tmp/git
    depends_on:
      terraform:
        condition: service_started

volumes:
  credential:
    external: true