apiVersion: v1
kind: Pod
metadata:
  name: fortune3s
  labels:
    name: fortune3s
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: fortune3s
    image: dangtong/fortune
    args: ["3"]
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 80
    volumeMounts: 
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true