apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
        - name: php-apache
          image: choiboyun/php-apache
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
          ports:
            - containerPort: 80