apiVersion: v1
kind: Pod
metadata:
  name: mongodb1
  labels:
    name: mongodb1
spec:
  volumes: 
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: mongodb-pvc1
  containers:
  - name: mongodb1
    image: mongo
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 27017
